# Comparison of predicted/measured thermal effects across TUS studies

In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:
import os
import pandas as pd

from usnm2p.logger import logger
from usnm2p.constants import *
from usnm2p.utils import compute_radiation_force, compute_temperature_increase
from usnm2p.fileops import get_data_root
from usnm2p.plotters import *

### Load data

In [3]:
fname = 'TUS_studies_temp_data.xlsx'
fpath = os.path.join(get_data_root(), fname)
data = pd.read_excel(fpath).set_index('Parameter')
data

                  Murphy 2022  our study
Parameter
f_0 (MHz)               0.623        2.1
PRF (Hz)              900.000      100.0
I_SPPA (W/cm2)          4.500       19.8
DC (%)                 20.000       80.0
duration (s)            5.000        0.2
measured ΔT (°C)        0.230        NaN

### Compute estimated radiation force and temperature rise for each study

In [4]:
data.loc['I_SPTA (W/cm2)'] = data.loc['I_SPPA (W/cm2)'] * data.loc['DC (%)'] / 100
data.loc['Frad (N/m3)'] = compute_radiation_force(
    data.loc['f_0 (MHz)'],
    data.loc['I_SPTA (W/cm2)']
)

data.loc['predicted Qheat (°C/s)'] = compute_heat_generation_rate(
    data.loc['f_0 (MHz)'],
    data.loc['I_SPTA (W/cm2)'],
)
data.loc['predicted ΔT (°C)'] = compute_temperature_increase(
    data.loc['f_0 (MHz)'],
    data.loc['I_SPTA (W/cm2)'],
    data.loc['duration (s)'],
)
data

                        Murphy 2022    our study
Parameter
f_0 (MHz)                  0.623000     2.100000
PRF (Hz)                 900.000000   100.000000
I_SPPA (W/cm2)             4.500000    19.800000
DC (%)                    20.000000    80.000000
duration (s)               5.000000     0.200000
measured ΔT (°C)           0.230000          NaN
I_SPTA (W/cm2)             0.900000    15.840000
Frad (N/m3)               42.808149  3656.703426
predicted Qheat (°C/s)     0.017433     1.489173
predicted ΔT (°C)          0.087167     0.297835